version: '3.8'

services:
  wordpress:
    # image: ghcr.io/avunu/wordpress:latest-php83
    image: localhost/avunu-wordpress:latest-php83
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpresspassword
      - WORDPRESS_DB_NAME=wordpress
    # override cmd with busybox
    command: /usr/bin/sh
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresspassword

volumes:
  db_data:
