x-common-env: &common-env
  WORDPRESS_HOME: http://localhost:8080
  WORDPRESS_SITE_URL: http://localhost:8080
  WORDPRESS_DB_HOST: db
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpresspassword
  WORDPRESS_DB_NAME: wordpress

services:
  wordpress:
    image: wordpress-php83:latest
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      <<: *common-env
    depends_on:
      - db

  worker:
    image: wordpress-php83:latest
    volumes:
      - ./wordpress:/var/www/html
    environment:
      <<: *common-env
      PROC_TYPE: worker
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresspassword

volumes:
  db_data: