name: Build and Push WordPress Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build Docker Images
      run: |
        nix build .#wordpress-php81 .#wordpress-php82 .#wordpress-php83

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push images to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        
        # Load and push images
        for result in result*; do
          IMAGE_NAME=$(cat $result/image-name)
          PHP_VERSION=$(echo $IMAGE_NAME | sed -n 's/.*-php\([0-9]\+\).*/\1/p')
          FULL_IMAGE_ID=$IMAGE_ID:php$PHP_VERSION
          
          # Load the image
          docker load < $result/${IMAGE_NAME}.tar.gz
          
          # Tag and push the image
          docker tag $IMAGE_NAME:latest $FULL_IMAGE_ID
          docker push $FULL_IMAGE_ID
          
          if [ "$VERSION" == "latest" ]; then
            docker tag $FULL_IMAGE_ID $IMAGE_ID:latest-php$PHP_VERSION
            docker push $IMAGE_ID:latest-php$PHP_VERSION
          fi
        done

        # Tag one version as the default latest
        DEFAULT_PHP_VERSION=83
        docker tag $IMAGE_ID:php$DEFAULT_PHP_VERSION $IMAGE_ID:latest
        docker push $IMAGE_ID:latest